# Generated by Django 5.2 on 2025-04-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CORREO', models.EmailField(max_length=254, unique=True)),
                ('CONTRASEÑA', models.CharField(max_length=128)),
                ('CARGO', models.CharField(choices=[('vendedor', 'Vendedor'), ('supervisor', 'Supervisor'), ('jefe', 'Jefe')], max_length=10)),
                ('SUPERVISOR', models.CharField(choices=[('Victor Murillo', 'Victor Murillo'), ('Marcos Nuñez', 'Marcos Nuñez'), ('Percy Apaza', 'Percy Apaza'), ('Gonzalo Alvarado', 'Gonzalo Alvarado')], max_length=50)),
                ('CODIGO_VEN', models.CharField(max_length=10, unique=True)),
                ('NOMBRE', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
