# Generated by Django 5.2 on 2025-04-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('proyect1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='CARGO',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='CORREO',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='NOMBRE',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='CODIGO_VEN',
        ),
        migrations.RemoveField(
            model_name='user',
            name='CONTRASEÑA',
        ),
        migrations.RemoveField(
            model_name='user',
            name='SUPERVISOR',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=2, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='codigo_ven',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.CharField(blank=True, choices=[('Victor Murillo', 'Victor Murillo'), ('Marcos Nuñez', 'Marcos Nuñez'), ('Percy Apaza', 'Percy Apaza'), ('Gonzalo Alvarado', 'Gonzalo Alvarado')], max_length=50, null=True),
        ),
    ]
