# Generated by Django 5.2 on 2025-04-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyect1', '0002_alter_user_options_rename_cargo_user_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='codigo_ven',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='codigo_vendedor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('supervisor', 'Supervisor'), ('jefe', 'Jefe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.CharField(blank=True, choices=[('Victor Murillo', 'Victor Murillo'), ('Marcos Nuñez', 'Marcos Nuñez'), ('Percy Apaza', 'Percy Apaza'), ('Gonzalo Alvarado', 'Gonzalo Alvarado')], max_length=100, null=True),
        ),
    ]
